# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0yyXftv_WLdRR2J3ryEzOJ3hVZrv8LL
"""

# Import necessary libraries
import pandas as pd
import statsmodels.api as sm
from google.colab import files

# Step 1: Upload the file
uploaded = files.upload()

# Step 2: Load the dataset
file_name = list(uploaded.keys())[0]  # Get the uploaded file name
data = pd.ExcelFile(file_name)  # Load the Excel file
df = data.parse('AmazonFoodCategory_1 Dataset')  # Load the relevant sheet

# Step 3: Data Preparation - Select relevant columns for regression
# Example: Using Sales Amount as dependent and Discount Amount, List Price, and Sales Quantity as independent
df = df[['Sales Amount', 'Discount Amount', 'List Price', 'Sales Quantity']]

# Drop rows with missing values
df = df.dropna()

# Step 4: Define dependent and independent variables
X = df[['Discount Amount', 'List Price', 'Sales Quantity']]  # Independent variables
y = df['Sales Amount']  # Dependent variable

# Add a constant to the independent variables (for the intercept)
X = sm.add_constant(X)

# Step 5: Fit the regression model
model = sm.OLS(y, X).fit()

# Step 6: Display the regression summary
print(model.summary())

